<?php

/**
 * Implements hook_views_api().
 */
function views_random_views_api() {
  return array(
    'api' => '3.0',
  );
}

/**
 *  Implements hook_preprocess_views_view().
 */
function views_random_preprocess_views_view(&$vars) {
  $view = $vars['view'];
  $name = $vars['name'];
  $display_id = $vars['display_id'];

  if ($view->query->pager->plugin_name == 'views_random') {
    drupal_add_js(drupal_get_path('module', 'views_random') . '/js/views-random.js');
    drupal_add_js(array('views_random' => array(
      $name => array(
        $display_id => $view->query->pager->options['items']
      )
    )), 'setting');
  }
}
